version: "3.8"
services:
  odin:
    build:
      context: . # The path of the Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    working_dir: /usr/src/app
    environment:
      SERVICE_NAME: blog-app
      DB_CONNECTION: mysql
      DB_DRIVER: mysql
      DB_HOST: db
      DB_PORT: 3306

      SLACK_HOOK: ${SLACK_HOOK}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
    networks:
      - app_network
  redis:
    image: redis:6.0.8
    ports: 
      - "6379"
    networks:
      - app_network
  nginx:
    build:
      context: .docker/nginx/. # The path of the Dockerfile
    volumes:
      - "./public:/usr/src/app/public"
    environment:
      NGINX_FPM_HOST: odin
      NGINX_ROOT: /usr/src/app/public
    ports:
      - "8000:80"
    depends_on:
      - odin
    networks:
      - app_network
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: odin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
#    ports:
#      - "3306:3306"
    volumes:
      - "./storage/db-data:/var/lib/mysql"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
